name: Contact
title: Contact
description:
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please contact me by email at contato <at> bpleonardo.com instead of opening an issue here.
