name: Contact
title: Contact
description: If you wish to contact me, open this issue.
assignees: bpleonardo
body:
  - type: textarea
    id: textarea-0
    attributes:
      label: Subject
      description: What you want to talk about? State if confidential.
